### ISSUE TITLE
Support for sequences of vectors

### ISSUE THREAD

**Issue by ftfish** [honeyext/cdtw#9]
Hi all,

It seems cdtw doesn't support running DTW with two sequences of feature vectors (e.g. MFCC). I get the following error:
```
Traceback (most recent call last):
  File "./s2f.py", line 161, in <module>
    d = U[b] - V
  File "./s2f.py", line 88, in __sub__
    compute_path = False)).get_dist()
  File "/my/path/to/python/python2.7/site-packages/cdtw/pydtw.py", line 12, in __init__
    cydtw.__init__(self, ref, query, settings)
  File "cdtw/cydtw.pyx", line 251, in cdtw.cydtw.cydtw.__init__ (cdtw/cydtw.c:4379)
  File "cdtw/cydtw.pyx", line 279, in cdtw.cydtw.cydtw._dtw (cdtw/cydtw.c:4989)
  File "/my/path/to/python/python2.7/site-packages/numpy/core/shape_base.py", line 278, in hstack
    return _nx.concatenate(arrs, 0)
ValueError: all the input arrays must have same number of dimensions
```

The code excerpt generating this error:
```
        return pydtw.dtw(this.stFeatures.T, that.stFeatures.T, pydtw.Settings(step = 'p0sym',     #Sakoe-Chiba symmetric step with slope constraint p = 0
                                window = 'palival', #type of the window
                                param = 2.0,        #window parameter
                                norm = False,       #normalization
                                dist='euclid',
                                compute_path = False)).get_dist()
```

`this.stFeatures.T` and `that.stFeatures.T` are numpy arrays and have shape (38, 13) and (65, 13) respectively.

Is this feature not supported or did I do something wrong?

Any help is appreciated, thank you!

**Comment by halachkin** [comment]
Hi @ftfish .
This is not supported, you need to write some wrapper for this. cdtw inputs should be two 1-dimensional array-like objects.

**Comment by ftfish** [comment]
Thank you for confirming. I see no simple way to add such a wrapper and unfortunately I don't have time to investigate further now.

Thank you.
